CREATE TABLE IF NOT EXISTS COURSE
(
  CourseCode int(11) NOT NULL UNIQUE,
  CourseName varchar(100) NOT NULL,
  CreditPoints int(8) DEFAULT NULL,
  Notes varchar(100) DEFAULT NULL,
  CONSTRAINT COURSE_PK PRIMARY KEY(CourseCode)
);
CREATE TABLE IF NOT EXISTS STUDENT
(
  StudentID int(11) NOT NULL UNIQUE,
  FirstName varchar(100) NOT NULL,
  LastName varchar(100) NOT NULL,
  Address varchar(100) DEFAULT NULL,
  City varchar(100) DEFAULT NULL,
  State varchar(100) DEFAULT NULL,
  PostCode varchar(100),
  Phone varchar(100),
  Email varchar(100),
  UNIQUE (Phone),
  UNIQUE(Email),
  CONSTRAINT STUDENT_PK PRIMARY KEY(StudentID)
);
CREATE TABLE IF NOT EXISTS UNIT
(
  UnitCode varchar(100) NOT NULL UNIQUE,
  UnitName varchar(100) NOT NULL,
  Prerequisites varchar(100) NOT NULL,
  Description varchar(200),
  CONSTRAINT UNIT_PK PRIMARY KEY(UnitCode)
);
CREATE TABLE IF NOT EXISTS TEACHER
(
  StaffID int(11) NOT NULL UNIQUE AUTO_INCREMENT,
  FirstName varchar(100) NOT NULL,
  LastName varchar(100) NOT NULL,
  Campus varchar(100),
  OfficeLocation varchar(100) DEFAULT NULL,
  Email varchar(100),
  Phone int(11) DEFAULT NULL,
  UNIQUE(Email),
  UNIQUE(Phone),
  CONSTRAINT TEACHER_PK PRIMARY KEY(StaffID)
);
CREATE TABLE IF NOT EXISTS COURSE_ENROLMENT
(
  StudentID int(11) DEFAULT NULL,
  CourseCode int(11) DEFAULT NULL,
  EnrolmentDate date,
  Status varchar(100),
  CONSTRAINT COURSE_ENROL_PK PRIMARY KEY(StudentID,CourseCode),
  CONSTRAINT COURSE_ENROL_STUDENT FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
  CONSTRAINT COURSE_ENROL_CODE FOREIGN KEY (CourseCode) REFERENCES COURSE(CourseCode)
);
CREATE TABLE IF NOT EXISTS UNIT_OFFERING
(
  UnitOfferingID int(8) NOT NULL UNIQUE AUTO_INCREMENT,
  UnitCode varchar(100) DEFAULT NULL,
  Year int(8) NOT NULL,
  Session int(8) NOT NULL,
  UnitAssessorID int(11) DEFAULT NULL,
  Locations varchar(100),
  CONSTRAINT UNIT_OFFER_PK PRIMARY KEY (UnitOfferingID),
  CONSTRAINT UNIT_OFFER_CODE FOREIGN KEY (UnitCode) REFERENCES UNIT(UnitCode),
  CONSTRAINT UNIT_OFFER_TEACHER FOREIGN KEY (UnitAssessorID) REFERENCES TEACHER(StaffID),
);
CREATE TABLE IF NOT EXISTS UNIT_ENROLMENT
(
  UnitEnrolmentID int(11) NOT NULL UNIQUE AUTO_INCREMENT,
  StudentID int(11) NOT NULL ,
  UnitOfferingID int(8) NOT NULL ,
  Year int(8) NOT NULL,
  Session int(8) NOT NULL,
  EnrolmentType varchar(100) NOT NULL,
  FinalGrade varchar(100),
  CONSTRAINT UNIT_ENROL_PK PRIMARY KEY (UnitEnrolmentID),
  CONSTRAINT UNIT_ENROL_STUDENT FOREIGN KEY(StudentID) REFERENCES STUDENT(StudentID),
  CONSTRAINT UNIT_ENROL_OFFER FOREIGN KEY (UnitOfferingID) REFERENCES UNIT_OFFERING(UnitOfferingID)
);
CREATE TABLE IF NOT EXISTS WORKSHOP
(
  WorkshopID int(8) NOT NULL UNIQUE AUTO_INCREMENT,
  UnitOfferingID int(8) DEFAULT NULL,
  Campus varchar(100),
  Location varchar(100),
  TeacherID int(11) DEFAULT NULL,
  Weekday varchar(100),
  ClassTimeStart TIME,
  ClassTimeEnd TIME,
  CONSTRAINT WORKSHOP_PK PRIMARY KEY(WorkshopID),
  CONSTRAINT WORK_UNIT_OFFER FOREIGN KEY (UnitOfferingID) REFERENCES UNIT_OFFERING(UnitOfferingID),
  CONSTRAINT WORKSHOP_TEACHER FOREIGN KEY (TeacherID) REFERENCES TEACHER(StaffID)
);
CREATE TABLE IF NOT EXISTS WORKSHOP_ENROLMENT
(
  WorkshopID int(8) DEFAULT NULL,
  StudentID int(11) DEFAULT NULL,
  CONSTRAINT WORKSHOP_ENROL_PK PRIMARY KEY(WorkshopID,StudentID),
  CONSTRAINT WORKSHOP_ENROL_ID FOREIGN KEY (WorkshopID) REFERENCES WORKSHOP(WorkshopID),
  CONSTRAINT WORKSHOP_ENROL_STUDENT FOREIGN KEY(StudentID) REFERENCES STUDENT(StudentID)
);
CREATE TABLE IF NOT EXISTS ASSESSMENT
(
  AssessmentID int(11) NOT NULL UNIQUE  AUTO_INCREMENT,
  UnitOfferingID int(8) DEFAULT NULL,
  AssessmentName varchar(100) NOT NULL,
  Description varchar(100) DEFAULT NULL,
  DueDate DATE DEFAULT NULL,
  PossibleMarks int(11) DEFAULT NULL,
  CONSTRAINT ASSESSMENT_PK PRIMARY KEY (AssessmentID),
  CONSTRAINT ASSESSMENT_UNITOFFERING FOREIGN KEY (UnitOfferingID) REFERENCES UNIT_OFFERING(UnitOfferingID)
);
CREATE TABLE IF NOT EXISTS STUDENT_ASSESSMENT
(
  AssessmentID int(11) DEFAULT NULL,
  StudentID int(11) DEFAULT NULL,
  DateSubmitted DATE DEFAULT NULL,
  DaysExtension int(11) DEFAULT NULL,
  MarkAwarded DECIMAL(5,2) DEFAULT NULL,
  CONSTRAINT STUDENT_ASSESSMENT_PK PRIMARY KEY(AssessmentID,StudentID),
  CONSTRAINT STUDENT_ASSESSMENT_ASSESSMENTID FOREIGN KEY (AssessmentID) REFERENCES ASSESSMENT(AssessmentID),
  CONSTRAINT ASSESSMENT_STUDENTID FOREIGN KEY(StudentID) REFERENCES STUDENT(StudentID)
);
