INSERT INTO `UNIT` (`UnitCode`, `UnitName`, `Prerequites`, `Description`) VALUES
('ARTD1007', 'Looking at Art', 'None', 'None'),
('ARTD1008', '3D Printing and Fabrication', 'None', 'None'),
('ARTD2003', 'Studio Practice II', 'None', 'None'),
('CMP71001', 'Cybersecurity', 'None', 'None'),
('CMP73001', 'Cybersecurity Management', 'None', 'None'),
('COM00207', 'Communication in Organisations', 'None', 'None'),
('COM00439 ', 'Theory in Practice: Issues in Media Studies', 'None', 'None'),
('COM00455', 'Online Media Design', 'None', 'None'),
('COMM1001', 'Communication in Organisations', 'None', 'None'),
('COMM2004', 'Online Media Design', 'None', 'None'),
('CSC00228', 'Database Systems I', 'None', 'None'),
('CSC00235', 'Applications Development', 'ISY10209', 'Web Development'),
('CSC00240', 'Data Communications and Networks', 'None', 'None'),
('CSC10210', 'Object Oriented Program Development', 'ISY00245', 'Principles of Programming'),
('CSC10214', 'Designing the User Experience', 'ISY10209', 'Web Development I'),
('CSC10215', 'Developing the User Experience', 'CSC10214', 'Designing the User Experience'),
('CSC10216', 'Object Oriented GUI Development', 'ISY00246', 'Client/Server Systems'),
('CSC10217', 'Web Development II', 'ISY10209', 'Web Development I'),
('CSC71001', 'Programming I', 'None', 'None'),
('CSC72001', 'Database Systems', 'ISY00243', 'Systems Analysis and Design'),
('CSC72002', 'Programming II', 'None', 'None'),
('EDU93104', 'Educational Investigation', 'None', 'None'),
('EDUC1001', 'Language and Learning in your Discipline', 'None', 'None'),
('EDUC1004', 'Understanding Children and Young People', 'None', 'None'),
('EDUC6012', 'Evaluation for Improved Teaching and Learning', 'None', 'None'),
('FOR00104', ' Forest Operations', 'None', 'None'),
('FOR00105', 'Plantation Silviculture', 'None', 'None'),
('FOR00107', 'Forest Health: Pest and Disease Management', 'None', 'None'),
('FOR00108', 'Agroforestry and Farm Forestry', 'None', 'None'),
('FORS2006', 'Forest Health: Pest and Disease Management', 'None', 'None'),
('INDG1002', 'Indigenous Knowledge', 'None', 'None'),
('INDG1003', 'The Mental Health of Australian Indigenous Peoples', 'None', 'None'),
('ISY00243', 'Systems Analysis and Design', 'None', 'None'),
('ISY00245', 'Principles of Programming', 'None', 'None'),
('ISY00246', 'Client/Server Systems', 'CSC10210', 'Object Oriented Program Development'),
('ISY00324', 'Digital Media I: Images, Text and Interface Design', 'None', 'None'),
('ISY00325', 'Digital Media II: Audio-Video Resources and Linear Scriptwriting', 'None', 'None'),
('ISY10058', 'Electronic Commerce Systems', 'ISY10209', 'Web Development I'),
('ISY10209', 'Web Development I', 'None', 'None'),
('ISY10212', 'Contemporary Issues in Multimedia and Information Technology', 'None', 'None'),
('ISY10221', 'Computing Project I: Analysis and Design', 'ISY00243 AND CSC00228 AND EITHER\r\nCSC00235 OR ISY00245', 'Systems Analysis and Design AND Database Systems I AND EITHER Applications Development OR  Principles of Programming'),
('ISY10222', 'Computing Project II: Development and Implementation', 'ISY10221', 'Computing Project I: Analysis and Design'),
('ISY330', 'Artificial Intelligence', 'None', 'None'),
('ISYS1002 ', 'Cybersecurity', 'None', 'None'),
('ISYS1003', 'Cybersecurity Management', 'None', 'None'),
('MAT10251', 'Statistical Analysis', 'None', 'None'),
('MDIA1001', 'Media Studies', 'None', 'None'),
('MNG10247', 'Managing Organisations', 'None', 'None');
